(setq inhibit-startup-screen t)
(set-default-font "Source Code Pro Semibold-10")
(menu-bar-mode 0)
(tool-bar-mode 0)
(ido-mode 1)
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(package-initialize)
(custom-set-variables
'(package-selected-packages (quote (evil elpy smex melancholy-theme))))
(custom-set-faces)
(require 'evil)
(evil-mode 1)
(load-theme 'melancholy t)
(scroll-bar-mode -1)
(global-set-key (kbd "M-x") 'smex)
(global-set-key (kbd "M-X") 'smex-major-mode-commands)
