# ZSH configs
#
export ZSH=$HOME/.oh-my-zsh
export LANG="en_US.UTF-8"

ZSH_THEME="powerlevel9k/powerlevel9k"

# Add wisely, as too many plugins slow down shell startup.
plugins=(git fast-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# Powerlevel9k configs
#
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
#POWERLEVEL9K_DISABLE_RPROMPT=true

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=( root_indicator dir vcs )
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=( status command_execution_time ssh time )

POWERLEVEL9K_ROOT_INDICATOR_FOREGROUND='white'
POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND='160'

POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND='black'
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND='purple'

POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND='white'
POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND='088'

POWERLEVEL9K_DIR_HOME_FOREGROUND='black'
POWERLEVEL9K_DIR_HOME_BACKGROUND='53'

POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='black'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='90'

POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='black'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='purple'

POWERLEVEL9K_STATUS_OK_FOREGROUND='070'
POWERLEVEL9K_STATUS_OK_BACKGROUND='237'

POWERLEVEL9K_STATUS_ERROR_FOREGROUND='196'
POWERLEVEL9K_STATUS_ERROR_BACKGROUND='237'

POWERLEVEL9K_VCS_CLEAN_FOREGROUND='black'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='019'

POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="  "
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2

POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=11
POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=1
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='088'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='white'

POWERLEVEL9K_CUSTOM_SEP_BACKGROUND='232'
POWERLEVEL9K_CUSTOM_SEP_FOREGROUND='232'

# Aliases
#
alias javar="java -jar"
alias ping=" ping -c 5"
alias "cd.."="cd .."
alias promptreload="source ~/.zshrc"
alias promptedit="vim ~/.zshrc"
